In [ ]:
import csv

In [ ]:
data = []
with open("/content/train.csv", "r") as file:
  reader = csv.reader(file)
  header = next(reader)
  for row in reader:
    data.append(row)

In [ ]:
age_index = header.index("Age")

In [ ]:
ages = []
for row in data:
  if row[age_index] != "":
    ages.append(float(row[age_index]))

In [ ]:
import numpy as np

In [ ]:
ages_np = np.array(ages)
mean_age = np.mean(ages_np)
median_age = np.median(ages_np)
std_age = np.std(ages_np)

In [ ]:
np.mean(ages_np)

np.float64(29.69911764705882)

In [ ]:
np.median(ages_np)

np.float64(28.0)

In [ ]:
np.std(ages_np)

np.float64(14.516321150817316)

In [ ]:
ages_np

array([22.  , 38.  , 26.  , 35.  , 35.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 31.  , 35.  ,
       34.  , 15.  , 28.  ,  8.  , 38.  , 19.  , 40.  , 66.  , 28.  ,
       42.  , 21.  , 18.  , 14.  , 40.  , 27.  ,  3.  , 19.  , 18.  ,
        7.  , 21.  , 49.  , 29.  , 65.  , 21.  , 28.5 ,  5.  , 11.  ,
       22.  , 38.  , 45.  ,  4.  , 29.  , 19.  , 17.  , 26.  , 32.  ,
       16.  , 21.  , 26.  , 32.  , 25.  ,  0.83, 30.  , 22.  , 29.  ,
       28.  , 17.  , 33.  , 16.  , 23.  , 24.  , 29.  , 20.  , 46.  ,
       26.  , 59.  , 71.  , 23.  , 34.  , 34.  , 28.  , 21.  , 33.  ,
       37.  , 28.  , 21.  , 38.  , 47.  , 14.5 , 22.  , 20.  , 17.  ,
       21.  , 70.5 , 29.  , 24.  ,  2.  , 21.  , 32.5 , 32.5 , 54.  ,
       12.  , 24.  , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  , 23.  ,
       19.  , 37.  , 16.  , 24.  , 22.  , 24.  , 19.  , 18.  , 19.  ,
       27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 , 40.5 , 51.  ,
       16.  , 30.  , 44.  , 40.  , 26.  , 17.  ,  1.  ,  9.  , 45.  ,
       28.  , 61.  ,  4.  ,  1.  , 21.  , 56.  , 18.  , 50.  , 30.  ,
       36.  ,  9.  ,  1.  ,  4.  , 45.  , 40.  , 36.  , 32.  , 19.  ,
       19.  ,  3.  , 44.  , 58.  , 42.  , 24.  , 28.  , 34.  , 45.5 ,
       18.  ,  2.  , 32.  , 26.  , 16.  , 40.  , 24.  , 35.  , 22.  ,
       30.  , 31.  , 27.  , 42.  , 32.  , 30.  , 16.  , 27.  , 51.  ,
       38.  , 22.  , 19.  , 20.5 , 18.  , 35.  , 29.  , 59.  ,  5.  ,
       24.  , 44.  ,  8.  , 19.  , 33.  , 29.  , 22.  , 30.  , 44.  ,
       25.  , 24.  , 37.  , 54.  , 29.  , 62.  , 30.  , 41.  , 29.  ,
       30.  , 35.  , 50.  ,  3.  , 52.  , 40.  , 36.  , 16.  , 25.  ,
       58.  , 35.  , 25.  , 41.  , 37.  , 63.  , 45.  ,  7.  , 35.  ,
       65.  , 28.  , 16.  , 19.  , 33.  , 30.  , 22.  , 42.  , 22.  ,
       26.  , 19.  , 36.  , 24.  , 24.  , 23.5 ,  2.  , 50.  , 19.  ,
        0.92, 17.  , 30.  , 30.  , 24.  , 18.  , 26.  , 28.  , 43.  ,
       26.  , 24.  , 54.  , 31.  , 40.  , 22.  , 27.  , 30.  , 22.  ,
       36.  , 61.  , 36.  , 31.  , 16.  , 45.5 , 38.  , 16.  , 29.  ,
       41.  , 45.  , 45.  ,  2.  , 24.  , 28.  , 25.  , 36.  , 24.  ,
       40.  ,  3.  , 42.  , 23.  , 15.  , 25.  , 28.  , 22.  , 38.  ,
       40.  , 29.  , 45.  , 35.  , 30.  , 60.  , 24.  , 25.  , 18.  ,
       19.  , 22.  ,  3.  , 22.  , 27.  , 20.  , 19.  , 42.  ,  1.  ,
       32.  , 35.  , 18.  ,  1.  , 36.  , 17.  , 36.  , 21.  , 28.  ,
       23.  , 24.  , 22.  , 31.  , 46.  , 23.  , 28.  , 39.  , 26.  ,
       21.  , 28.  , 20.  , 34.  , 51.  ,  3.  , 21.  , 33.  , 44.  ,
       34.  , 18.  , 30.  , 10.  , 21.  , 29.  , 28.  , 18.  , 28.  ,
       19.  , 32.  , 28.  , 42.  , 17.  , 50.  , 14.  , 21.  , 24.  ,
       64.  , 31.  , 45.  , 20.  , 25.  , 28.  ,  4.  , 13.  , 34.  ,
        5.  , 52.  , 36.  , 30.  , 49.  , 29.  , 65.  , 50.  , 48.  ,
       34.  , 47.  , 48.  , 38.  , 56.  ,  0.75, 38.  , 33.  , 23.  ,
       22.  , 34.  , 29.  , 22.  ,  2.  ,  9.  , 50.  , 63.  , 25.  ,
       35.  , 58.  , 30.  ,  9.  , 21.  , 55.  , 71.  , 21.  , 54.  ,
       25.  , 24.  , 17.  , 21.  , 37.  , 16.  , 18.  , 33.  , 28.  ,
       26.  , 29.  , 36.  , 54.  , 24.  , 47.  , 34.  , 36.  , 32.  ,
       30.  , 22.  , 44.  , 40.5 , 50.  , 39.  , 23.  ,  2.  , 17.  ,
       30.  ,  7.  , 45.  , 30.  , 22.  , 36.  ,  9.  , 11.  , 32.  ,
       50.  , 64.  , 19.  , 33.  ,  8.  , 17.  , 27.  , 22.  , 22.  ,
       62.  , 48.  , 39.  , 36.  , 40.  , 28.  , 24.  , 19.  , 29.  ,
       32.  , 62.  , 53.  , 36.  , 16.  , 19.  , 34.  , 39.  , 32.  ,
       25.  , 39.  , 54.  , 36.  , 18.  , 47.  , 60.  , 22.  , 35.  ,
       52.  , 47.  , 37.  , 36.  , 49.  , 49.  , 24.  , 44.  , 35.  ,
       36.  , 30.  , 27.  , 22.  , 40.  , 39.  , 35.  , 24.  , 34.  ,
       26.  ,  4.  , 26.  , 27.  , 42.  , 20.  , 21.  , 21.  , 61.  ,
       57.  , 21.  , 26.  , 80.  , 51.  , 32.  ,  9.  , 28.  , 32.  ,
       31.  , 41.  , 20.  , 24.  ,  2.  ,  0.75, 48.  , 19.  , 56.  ,
       23.  , 18.  , 21.  , 18.  , 24.  , 32.  , 23.  , 58.  , 50.  ,
       40.  , 47.  , 36.  , 20.  , 32.  , 25.  , 43.  , 40.  , 31.  ,
       70.  , 31.  , 18.  , 24.5 , 18.  , 43.  , 36.  , 27.  , 20.  ,
       14.  , 60.  , 25.  , 14.  , 19.  , 18.  , 15.  , 31.  ,  4.  ,
       25.  , 60.  , 52.  , 44.  , 49.  , 42.  , 18.  , 35.  , 18.  ,
       25.  , 26.  , 39.  , 45.  , 42.  , 22.  , 24.  , 48.  , 29.  ,
       52.  , 19.  , 38.  , 27.  , 33.  ,  6.  , 17.  , 34.  , 50.  ,
       27.  , 20.  , 30.  , 25.  , 25.  , 29.  , 11.  , 23.  , 23.  ,
       28.5 , 48.  , 35.  , 36.  , 21.  , 24.  , 31.  , 70.  , 16.  ,
       30.  , 19.  , 31.  ,  4.  ,  6.  , 33.  , 23.  , 48.  ,  0.67,
       28.  , 18.  , 34.  , 33.  , 41.  , 20.  , 36.  , 16.  , 51.  ,
       30.5 , 32.  , 24.  , 48.  , 57.  , 54.  , 18.  ,  5.  , 43.  ,
       13.  , 17.  , 29.  , 25.  , 25.  , 18.  ,  8.  ,  1.  , 46.  ,
       16.  , 25.  , 39.  , 49.  , 31.  , 30.  , 30.  , 34.  , 31.  ,
       11.  ,  0.42, 27.  , 31.  , 39.  , 18.  , 39.  , 33.  , 26.  ,
       39.  , 35.  ,  6.  , 30.5 , 23.  , 31.  , 43.  , 10.  , 52.  ,
       27.  , 38.  , 27.  ,  2.  ,  1.  , 62.  , 15.  ,  0.83, 23.  ,
       18.  , 39.  , 21.  , 32.  , 20.  , 16.  , 30.  , 34.5 , 17.  ,
       42.  , 35.  , 28.  ,  4.  , 74.  ,  9.  , 16.  , 44.  , 18.  ,
       45.  , 51.  , 24.  , 41.  , 21.  , 48.  , 24.  , 42.  , 27.  ,
       31.  ,  4.  , 26.  , 47.  , 33.  , 47.  , 28.  , 15.  , 20.  ,
       19.  , 56.  , 25.  , 33.  , 22.  , 28.  , 25.  , 39.  , 27.  ,
       19.  , 26.  , 32.  ])

Fare

In [ ]:
fare_index = header.index("Fare")
fares = []
for row in data:
    fares.append(float(row[fare_index]))

In [ ]:
fares_np = np.array(fares)

In [ ]:
top_10 = np.percentile(fares_np, 90)
bottom_10 = np.percentile(fares_np, 10)

In [ ]:
top_passengers = fares_np[fares_np >= top_10]
low_passengers = fares_np[fares_np <= bottom_10]

In [ ]:
survival_index = header.index("Survived")

ages = []
survival = []

for row in data:
    if row[age_index] != "":
        ages.append(float(row[age_index]))
        survival.append(int(row[survival_index]))

ages = np.array(ages)
survival = np.array(survival)

In [ ]:
child = ages < 15
adult = (ages >= 15) & (ages <= 60)
senior = ages > 60

In [ ]:
child_survival = np.mean(survival[child])
adult_survival = np.mean(survival[adult])
senior_survival = np.mean(survival[senior])

In [ ]:
child_survival

np.float64(0.5769230769230769)

In [ ]:
adult_survival

np.float64(0.39087947882736157)

In [ ]:
senior_survival

np.float64(0.22727272727272727)

Is age linearly related to survival? Justify statistically.
-->The relationship between age and survival is not linear.

Part 2

In [1]:
import pandas as pd

df = pd.read_csv("train.csv")

In [2]:
df['Age'] = df.groupby('Pclass')['Age'].transform(lambda x: x.fillna(x.median()))
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

/tmp/ipykernel_1127/1026403145.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)
df['FarePerPerson'] = df['Fare'] / df['FamilySize']

In [7]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,IsAlone,FarePerPerson
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,0,3.62500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,0,35.64165
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,7.92500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,0,26.55000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,1,8.05000

In [8]:
df['AgeGroup'] = pd.cut(df['Age'],
                       bins=[0, 15, 60, 100],
                       labels=['Child', 'Adult', 'Senior'])

df['FareGroup'] = pd.qcut(df['Fare'], 3, labels=['Low', 'Medium', 'High'])

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,IsAlone,FarePerPerson,AgeGroup,FareGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,0,3.62500,Adult,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,0,35.64165,Adult,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,7.92500,Adult,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,0,26.55000,Adult,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,1,8.05000,Adult,Low

In [11]:
pd.pivot_table(df, values='Survived', index='Sex', columns='Pclass', aggfunc='mean')

pd.pivot_table(df, values='Survived', index='FareGroup', columns='Embarked', aggfunc='mean')

/tmp/ipykernel_1127/1028202498.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(df, values='Survived', index='FareGroup', columns='Embarked', aggfunc='mean')

Embarked          C         Q         S
FareGroup
Low        0.250000  0.388889  0.142202
Medium     0.538462  0.500000  0.373391
High       0.677419  0.142857  0.517949

In [12]:
corr = df.corr(numeric_only=True)

In [13]:
corr['Survived'].sort_values(ascending=False)

Survived         1.000000
Fare             0.257307
FarePerPerson    0.221600
Parch            0.081629
FamilySize       0.016639
PassengerId     -0.005007
SibSp           -0.035322
Age             -0.047255
IsAlone         -0.203367
Pclass          -0.338481
Name: Survived, dtype: float64

PART 3 – NumPy-Based Survival Model

In [14]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['AgeGroup'] = df['AgeGroup'].map({'Child': 2, 'Adult': 1, 'Senior': 0})
df['FareGroup'] = df['FareGroup'].map({'Low': 0, 'Medium': 1, 'High': 2})

In [16]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,IsAlone,FarePerPerson,AgeGroup,FareGroup
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,2,0,3.62500,1,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,2,0,35.64165,1,2
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,7.92500,1,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,2,0,26.55000,1,2
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,1,1,8.05000,1,0

In [18]:
def normalize(x):
    return (x - x.min()) / (x.max() - x.min())

df['Pclass'] = normalize(df['Pclass'])
df['Fare'] = normalize(df['Fare'])
df['FamilySize'] = normalize(df['FamilySize'])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,IsAlone,FarePerPerson,AgeGroup,FareGroup
0,1,0,1.0,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,0.014151,NaN,S,0.1,0,3.62500,1,0
1,2,1,0.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,0.139136,C85,C,0.1,0,35.64165,1,2
2,3,1,1.0,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,0.015469,NaN,S,0.0,1,7.92500,1,0
3,4,1,0.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,0.103644,C123,S,0.1,0,26.55000,1,2
4,5,0,1.0,"Allen, Mr. William Henry",0,35.0,0,0,373450,0.015713,NaN,S,0.0,1,8.05000,1,0

In [22]:
df['AgeGroup'].dtype

CategoricalDtype(categories=[2, 1, 0], ordered=True, categories_dtype=int64)

In [24]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['AgeGroup'] = df['AgeGroup'].cat.codes

In [25]:
score = (
    0.35 * df['Sex'] +
    0.25 * (1 - df['Pclass']) +
    0.15 * df['Fare'] +
    0.15 * df['AgeGroup'] +
    0.10 * df['FamilySize']
)

In [26]:
df['Prediction'] = (score > 0.5).astype(int)

In [27]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,IsAlone,FarePerPerson,AgeGroup,FareGroup,Prediction
0,1,0,1.0,"Braund, Mr. Owen Harris",NaN,22.0,1,0,A/5 21171,0.014151,NaN,S,0.1,0,3.62500,1,0,0
1,2,1,0.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",NaN,38.0,1,0,PC 17599,0.139136,C85,C,0.1,0,35.64165,1,2,0
2,3,1,1.0,"Heikkinen, Miss. Laina",NaN,26.0,0,0,STON/O2. 3101282,0.015469,NaN,S,0.0,1,7.92500,1,0,0
3,4,1,0.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",NaN,35.0,1,0,113803,0.103644,C123,S,0.1,0,26.55000,1,2,0
4,5,0,1.0,"Allen, Mr. William Henry",NaN,35.0,0,0,373450,0.015713,NaN,S,0.0,1,8.05000,1,0,0

In [29]:
import numpy as np

y_true = df['Survived'].values
y_pred = df['Prediction'].values

TP = np.sum((y_true == 1) & (y_pred == 1))
TN = np.sum((y_true == 0) & (y_pred == 0))
FP = np.sum((y_true == 0) & (y_pred == 1))
FN = np.sum((y_true == 1) & (y_pred == 0))

accuracy = (TP + TN) / len(y_true)
precision = TP / (TP + FP)
recall = TP / (TP + FN)

/tmp/ipykernel_1127/2995249546.py:12: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)

Does your handcrafted score outperform random guessing significantly? -->
Model performs significantly better than random (50%), proving handcrafted features capture survival patterns.

Bonus Challenge (Very Difficult)

In [30]:
import pandas as pd
import numpy as np

df = pd.read_csv("train.csv")

Part 1-a

In [31]:
survived = df["Survived"].values
sex = df["Sex"].values

In [32]:
sex_encoded = np.where(sex == "female", 1, 0)

In [33]:
female_mask = sex_encoded == 1
male_mask = sex_encoded == 0

female_survival = survived[female_mask].mean()
male_survival = survived[male_mask].mean()

print("Female Survival Rate:", female_survival)
print("Male Survival Rate:", male_survival)

Female Survival Rate: 0.7420382165605095
Male Survival Rate: 0.18890814558058924

Part 1-b

In [34]:
pclass = df["Pclass"].values

In [35]:
class_1_survival = survived[pclass == 1].mean()
class_2_survival = survived[pclass == 2].mean()
class_3_survival = survived[pclass == 3].mean()

print("Class 1 Survival:", class_1_survival)
print("Class 2 Survival:", class_2_survival)
print("Class 3 Survival:", class_3_survival)

Class 1 Survival: 0.6296296296296297
Class 2 Survival: 0.47282608695652173
Class 3 Survival: 0.24236252545824846

In [36]:
unique_classes = np.unique(pclass)

survival_by_class = {
    cls: survived[pclass == cls].mean()
    for cls in unique_classes
}

print(survival_by_class)

{np.int64(1): np.float64(0.6296296296296297), np.int64(2): np.float64(0.47282608695652173), np.int64(3): np.float64(0.24236252545824846)}

Part 2

In [37]:
df["Sex"] = np.where(df["Sex"] == "female", 1, 0)
df["AgeGroup"] = np.where(df["Age"] < 15, 1, 0)
df["FamilySize"] = df["SibSp"] + df["Parch"]

In [38]:
score = (
    0.35 * df["Sex"].values +
    0.25 * (1 - df["Pclass"].values / 3) +
    0.15 * df["Fare"].values / df["Fare"].max() +
    0.15 * df["AgeGroup"].values +
    0.10 * df["FamilySize"].values / df["FamilySize"].max()
)

Part 3

In [39]:
def predict_survival(passenger):
    """
    Predict survival using weighted scoring model.
    passenger: dictionary with keys:
    Sex, Pclass, Fare, Age, SibSp, Parch
    """

    # Encode gender
    sex = 1 if passenger["Sex"] == "female" else 0

    # Normalize class (1 best → higher score)
    class_score = 1 - (passenger["Pclass"] / 3)

    # Age group
    age_group = 1 if passenger["Age"] < 15 else 0

    # Family size
    family_size = passenger["SibSp"] + passenger["Parch"]

    # Normalize values (assume max fare 512, max family 10 approx)
    fare_norm = passenger["Fare"] / 512
    family_norm = family_size / 10

    score = (
        0.35 * sex +
        0.25 * class_score +
        0.15 * fare_norm +
        0.15 * age_group +
        0.10 * family_norm
    )

    return 1 if score > 0.5 else 0

In [40]:
new_passenger = {
    "Sex": "female",
    "Pclass": 1,
    "Fare": 100,
    "Age": 25,
    "SibSp": 0,
    "Parch": 0
}

prediction = predict_survival(new_passenger)
print("Predicted Survival:", prediction)

Predicted Survival: 1